name: anythingllm

networks:
  anything-llm:
    driver: bridge

services:
  anything-llm:
    container_name: anythingllm
    image: mintplexlabs/anythingllm
    cap_add:
      - SYS_ADMIN
    environment:
      - STORAGE_DIR=/app/server/storage
      - UID=1000
      - GID=1000
    volumes:
      - anythingllm-storage:/app/server/storage
      - anythingllm-hotdir:/app/collector/hotdir
      - anythingllm-outputs:/app/collector/outputs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anythingllm.rule=Host(`anything-llm.stevesbbs.com\
        `)"
      - "traefik.http.services.anythingllm.loadbalancer.server.port=3001"
    ports:
      - "8006:3001"
    networks:
      - anything-llm
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  anythingllm-storage:
  anythingllm-hotdir:
  anythingllm-outputs:
